apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/jl-jenkins-bot/dp-jx-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    envOrganisation: jl-jenkins-bot
    gitServer: https://github.com
    helmTemplate: true
    importMode: Jenkinsfile
    kubeProvider: gke
    pipelineUsername: jl-jenkins-bot
    promotionEngine: Jenkins
    prowConfig: Legacy
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://jx-boot-cluster-lts-4e46def5-11ce-4933-b221-19a6295084ac
      classifier: default
    - bucketUrl: gs://jx-boot-cluster-lts-4e46def5-11ce-4933-b221-19a6295084ac
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
status: {}
